version: '3.4'
services:

  db:
    image: postgres:10-alpine
    container_name: db
    hostname: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=dbs
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  nx:
    driver: bridge
