version: '3.4'
services:

  db:
    image: postgres:10-alpine
    container_name: db
    hostname: db
    restart: always
    networks:
      - kaizen-net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kaizen
      - POSTGRES_PASSWORD=KZ@db!123456789
      - POSTGRES_DB=ksdb
    volumes:
      - './postgres/pg_db:/var/lib/postgresql'
      - './postgres/pg_data:/var/lib/postgresql/data'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  kaizen-net:
    driver: bridge
