#Spring Datasource
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbs
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  #JPA Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
